Responding to review comments
1. Removed declaration of i from test_all, test_any, and the integer test_max
and test_min
2. Removed tolerance from the real test_min and test_max
3. Updated build-tests.yaml to use grep -q instead of just plain grep. Note
that on my mac, grep -q initially resulted in

error: write on a pipe with no reader

But that message went away if I sent stderr -> stdout (via 2>&1). Hopefully the
github runners are okay with that